import akshare
df = akshare.stock_zh_a_spot_em()
print(f'Total stocks: {len(df)}')
rise = len(df[df['涨跌幅'] > 0])
fall = len(df[df['涨跌幅'] < 0])
print(f'Advancing: {rise}, Declining: {fall}')
top_gainers = df[df['涨跌幅'] > 9.5].head(10)
print('Top gainers:', top_gainers[['名称', '最新价', '涨跌幅']].to_string())
top_losers = df[df['涨跌幅'] < -9.5].head(10)
print('Top losers:', top_losers[['名称', '最新价', '涨跌幅']].to_string())
volume_sum = df['成交量'].sum()
amount_sum = df['成交额'].sum()
print(f'Total volume: {volume_sum:,}')
print(f'Total amount: ¥{amount_sum:,.0f}')